=== Bearaffairs/MEGA65-Compatible/old_files/temp.xsd
<?xml version="1.0"?>
<!-- 
Comment
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		>

		<!-- Defining simple elements -->
		
			<xs:element name="TITLE" type="xs:string" />
			<xs:element name="DEVELOPER" type="xs:string" />
			<xs:element name="GENRE" type="xs:string" />
			<xs:element name="YEAR" type="xs:integer" />
			<xs:element name="COMPATIBILITY" type="xs:string" />
			<xs:element name="ISSUES" type="xs:string" />
			
			<!-- Defining complex elements -->
			
			<xs:element name="Game">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="TITLE" />
						<xs:element ref="DEVELOPER" />
						<xs:element ref="GENRE" />
						<xs:element ref="YEAR" />
						<xs:element ref="COMPATIBILITY" />
						<xs:element ref="ISSUES" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
				
				
			<xs:element name ="Library">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="Game" maxOccurs="unbounded" />
					</xs:sequence>	
				</xs:complexType>
			</xs:element>	

</xs:schema>

=== Bearaffairs/MEGA65-Compatible/libraryw_xsd.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 
Comment
-->
<Library
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="temp.xsd">

	<Game>
		<TITLE> Boulder Dash </TITLE>
		<DEVELOPER> First Star Software  </DEVELOPER>
		<GENRE> Puzzle </GENRE>
		<YEAR> 1984 </YEAR>
		<COMPATIBILITY> Yes </COMPATIBILITY>
		<ISSUES> Slight jittering on vertical scrolling </ISSUES>
	</Game>


</Library>
